=== pawel33317/XML-programy-kompilator-dtd-xml-schema-srcml/3 XMLSchema/zad2/sad.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"> 
	<xsd:element name="SAD" type="sad_type"/> 
	
	<xsd:element name="Zgloszenie" type="typ_zgloszenia"/> 
	
	<xsd:complexType name="sad_type"> 
		<xsd:sequence> 
			<xsd:element ref="Zgloszenie"/>  
		</xsd:sequence> 
		<xsd:attribute name="EmailPodmiotu" type="email"/> 
	</xsd:complexType> 

	<xsd:simpleType name="email"> 
		<xsd:restriction base="xsd:string"> 
			<xsd:pattern value="[^@]+@[^\.]+\..+"/> 
		</xsd:restriction> 
	</xsd:simpleType> 

	<xsd:complexType name="typ_zgloszenia"> 
		<xsd:sequence> 
			<xsd:element name="UC">
				<xsd:complexType> 
					<xsd:attribute name="UCZgloszenia" type="xsd:decimal" use="required"/> 
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="ZglaszajacyPrzedstawiciel">
				<xsd:complexType> 
					<xsd:attribute name="REGON" type="xsd:decimal"/> 
					<xsd:attribute name="NrWpisu" type="xsd:string"/> 
				</xsd:complexType> 
			</xsd:element>

			<xsd:element name="Transport">
				<xsd:complexType> 
					<xsd:attribute name="Rodzaj" type="xsd:decimal"/> 
				</xsd:complexType> 
			</xsd:element>
			<xsd:element name="TransportNaGranicy">
				<xsd:complexType> 
					<xsd:attribute name="Rodzaj" type="xsd:decimal"/> 
					<xsd:attribute name="Kraj" type="xsd:NMTOKEN" default="PL"/> 
				</xsd:complexType> 
			</xsd:element>	
			<xsd:element name="WarunkiDostawy">
				<xsd:complexType> 
					<xsd:attribute name="Kod" type="xsd:NMTOKEN"/> 
				</xsd:complexType> 
			</xsd:element>
			<xsd:element name="WartoscTowarow">
				<xsd:complexType> 
					<xsd:attribute name="Waluta" type="xsd:NMTOKEN"/>
				</xsd:complexType> 
			</xsd:element> 
			<xsd:element name="Towar" type="typ_towar" minOccurs="1" maxOccurs="unbounded"/>
			<xsd:element name="MiejsceData">
				<xsd:complexType> 
					<xsd:attribute name="Data" type="xsd:date"/>
					<xsd:attribute name="Miejsce" type="xsd:string"/>
					<xsd:attribute name="NazwiskoImie" type="xsd:string"/>
					<xsd:attribute name="Telefon" type="xsd:string"/>
				</xsd:complexType> 
			</xsd:element>
		</xsd:sequence> 
		<xsd:attribute name="P1a" type="xsd:NMTOKEN"/> 
		<xsd:attribute name="P1b" type="xsd:NMTOKEN"/> 
		<xsd:attribute name="P1c" type="validPC1"/>
		<xsd:attribute name="KrajPrzeznaczenia" type="xsd:NMTOKEN"/> 
		<xsd:attribute name="NrWlasny" type="xsd:string"/> 
		<xsd:attribute name="LiczbaPozycji" type="xsd:integer"/> 
		<xsd:attribute name="Kontenery" type="xsd:integer"/> 
		<xsd:attribute name="KrajWysylki" type="xsd:NMTOKEN"/> 
		<xsd:attribute name="RodzajTransakcji" type="xsd:integer"/> 
	</xsd:complexType>
	
	
	<xsd:simpleType name="validPC1"> 
		<xsd:restriction base="xsd:string"> 
			<xsd:pattern value="\d{2}-\d{2}"/> 
		</xsd:restriction> 
	</xsd:simpleType> 
	
	
	<xsd:complexType name="typ_towar"> 
		<xsd:sequence>  
			<xsd:element name="WartoscTowaru" type="typ_WartoscTowaru" minOccurs="1"  maxOccurs="1"/> 
		</xsd:sequence> 
		<xsd:attribute name="PozId" type="xsd:integer"/> 
		<xsd:attribute name="MasaBrutto" type="xsd:decimal"/> 
		<xsd:attribute name="MasaNetto" type="xsd:decimal"/> 
		<xsd:attribute name="KodTowarowy" type="xsd:integer"/> 
		<xsd:attribute name="OpisTowaru" type="xsd:string"/> 
		<xsd:attribute name="KrajPochodzenia" type="xsd:string"/> 
		<xsd:attribute name="Procedura" type="xsd:integer"/> 
	</xsd:complexType> 

	<xsd:complexType name="typ_WartoscTowaru"> 

		<xsd:attribute name="WartoscPozycji" type="xsd:decimal"/> 
		<xsd:attribute name="WartoscStatystyczna" type="xsd:decimal"/> 
	</xsd:complexType>
	
</xsd:schema>

=== pawel33317/XML-programy-kompilator-dtd-xml-schema-srcml/3 XMLSchema/zad2/sad.xml
<?xml version="1.0" encoding="utf-8"?>
<SAD EmailPodmiotu="xxx_xxxxxx@xxx.xx"   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sad.xsd">
	<Zgloszenie P1a="IM" P1b="D" P1c="06-09" KrajPrzeznaczenia="AD" NrWlasny="09S0000002" LiczbaPozycji="12" Kontenery="0" KrajWysylki="PL" RodzajTransakcji="11">
		<UC UCZgloszenia="350000"></UC>    
		<ZglaszajacyPrzedstawiciel  REGON="00000000000002000" NrWpisu="SASP/2009/XXX/XXXXX/XXXXXXX" />        
		<Transport Rodzaj="3" />
		<TransportNaGranicy Rodzaj="3" Kraj="PL" />
		<WarunkiDostawy Kod="EXW" />
		<WartoscTowarow Waluta="USD" />
		<Towar PozId="1" MasaBrutto="16998.000" MasaNetto="12793.000" KodTowarowy="87082990" OpisTowaru="Stalowe bloki" KrajPochodzenia="PL" Procedura="1000">
			<WartoscTowaru WartoscPozycji="60000.00" WartoscStatystyczna="240000" />
		</Towar>
		<Towar PozId="2" MasaBrutto="16998.000" MasaNetto="12793.000" KodTowarowy="87082990" OpisTowaru="Podpory B" KrajPochodzenia="PL" Procedura="1000">
			<WartoscTowaru WartoscPozycji="60000.00" WartoscStatystyczna="240000" />
		</Towar>
		<Towar PozId="3" MasaBrutto="16998.000" MasaNetto="12793.000" KodTowarowy="87082990" OpisTowaru="Podpory A" KrajPochodzenia="PL" Procedura="1000">
			<WartoscTowaru WartoscPozycji="60000.00" WartoscStatystyczna="240000" />
		</Towar>
		<Towar PozId="4" MasaBrutto="16998.000" MasaNetto="12793.000" KodTowarowy="87082990" OpisTowaru="Mocowania" KrajPochodzenia="PL" Procedura="1000">
			<WartoscTowaru WartoscPozycji="60000.00" WartoscStatystyczna="240000" />
		</Towar>
		<Towar PozId="5" MasaBrutto="16998.000" MasaNetto="12793.000" KodTowarowy="87082990" OpisTowaru="Zbrojenie" KrajPochodzenia="PL" Procedura="1000">
			<WartoscTowaru WartoscPozycji="60000.00" WartoscStatystyczna="240000" />
		</Towar>
		<Towar PozId="6" MasaBrutto="16998.000" MasaNetto="12793.000" KodTowarowy="87082990" OpisTowaru="Stalowe kątowniki" KrajPochodzenia="PL" Procedura="1000">
			<WartoscTowaru WartoscPozycji="60000.00" WartoscStatystyczna="240000" />
		</Towar>
		<Towar PozId="7" MasaBrutto="16998.000" MasaNetto="12793.000" KodTowarowy="87082990" OpisTowaru="Złączki" KrajPochodzenia="PL" Procedura="1000">
			<WartoscTowaru WartoscPozycji="60000.00" WartoscStatystyczna="240000" />
		</Towar>
		<Towar PozId="8" MasaBrutto="16998.000" MasaNetto="12793.000" KodTowarowy="87082990" OpisTowaru="Złączki miedziane jednokrotne" KrajPochodzenia="PL" Procedura="1000">
			<WartoscTowaru WartoscPozycji="60000.00" WartoscStatystyczna="240000" />
		</Towar>
		<Towar PozId="9" MasaBrutto="16998.000" MasaNetto="12793.000" KodTowarowy="87082990" OpisTowaru="Podpory C" KrajPochodzenia="PL" Procedura="1000">
			<WartoscTowaru WartoscPozycji="60000.00" WartoscStatystyczna="240000" />
		</Towar>
		<Towar PozId="10" MasaBrutto="16998.000" MasaNetto="12793.000" KodTowarowy="87082990" OpisTowaru="Podpory G" KrajPochodzenia="PL" Procedura="1000">
			<WartoscTowaru WartoscPozycji="60000.00" WartoscStatystyczna="240000" />
		</Towar>
		<Towar PozId="11" MasaBrutto="16998.000" MasaNetto="12793.000" KodTowarowy="87082990" OpisTowaru="Gotowe konstrukcje mocujące Y" KrajPochodzenia="PL" Procedura="1000">
			<WartoscTowaru WartoscPozycji="60000.00" WartoscStatystyczna="240000" />
		</Towar>
		<Towar PozId="12" MasaBrutto="16998.000" MasaNetto="12793.000" KodTowarowy="87082990" OpisTowaru="Gotowe konstrukcje mocujące X" KrajPochodzenia="PL" Procedura="1000">
			<WartoscTowaru WartoscPozycji="60000.00" WartoscStatystyczna="240000" />
		</Towar>
		<MiejsceData Data="2006-04-21" Miejsce="Miejsce" NazwiskoImie="XXXXXX Maria" Telefon="(012) 1234567" />
	</Zgloszenie>
</SAD>
