=== pawel33317/XML-programy-kompilator-dtd-xml-schema-srcml/2 DTD/zad2/product.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT catalog (product+)>

<!ELEMENT product (specifications+,options?,price+,notes?)>
<!ATTLIST product
name CDATA #IMPLIED
category (handtool|table|shop-professional) "handtool"
partnum CDATA #IMPLIED
plant (pittsburgh|milwaukee|chicago) "chicago"
inventory (instock|backordered|discontinued) "instock">

<!ELEMENT specifications (#PCDATA)>
<!ATTLIST specifications
weight CDATA #IMPLIED
power CDATA #IMPLIED>

<!ELEMENT options (#PCDATA)>
<!ATTLIST options
finish (metal|polished|matte) "matte"
adapter (included|optional|notapplicable) "included"
case (hardshell|soft|notapplicable) "hardshell">

<!ELEMENT price (#PCDATA)>
<!ATTLIST price
msrp CDATA #IMPLIED
wholesale CDATA #IMPLIED
street CDATA #IMPLIED
shipping CDATA #IMPLIED>

<!ELEMENT notes (#PCDATA)>
<!ENTITY author "john doe">
<!ENTITY company "jd power tools, inc.">
<!ENTITY email "jd@jd-tools.com">

=== pawel33317/XML-programy-kompilator-dtd-xml-schema-srcml/2 DTD/zad2/xml2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "product.dtd">
<catalog>
	<product name="Monitor" category="table" partnum="CZ432" plant="chicago" inventory="instock">
		<specifications weight="2.22" power="456">Specyfikacja v1.1</specifications>
		<options finish="polished" adapter="included" case="hardshell"/>
		<price msrp="888" wholesale="999" street="Wierzbowa" shipping="yes">345zl</price>
		<notes>Autor: &author; Firma: &company;Email: &email;</notes>
	</product>
	<product name="Krzeslo" category="table" partnum="KK435" plant="milwaukee" inventory="backordered">
		<specifications weight="12.22" power="4256">Using spec</specifications>
		<options finish="polished" adapter="included" case="notapplicable"/>
		<price msrp="55" wholesale="44" street="Makaronowa" shipping="19">452$</price>
		<price msrp="56" wholesale="45" street="Makaronowa" shipping="22">452$</price>
		<notes>Autor: &author; Firma: &company;Email: &email;</notes>
	</product>
</catalog>
