=== pawel33317/XML-programy-kompilator-dtd-xml-schema-srcml/4 XSLT/zml4/zad3.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"> 
	<xsd:element name="filmy" type="typ_filmy"/> 
	<xsd:complexType name="typ_filmy"> 
		<xsd:sequence> 
			<xsd:element name="film" type="film_rozwiniecie" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence> 
		<xsd:attribute name="katalog" type="xsd:string" fixed="darmowe"/> 
	</xsd:complexType> 

	<xsd:element name="tytul" type="xsd:string"/> 
	<xsd:complexType name="film_rozwiniecie"> 
		<xsd:sequence> 
			<xsd:element ref="tytul" />
			<xsd:element name="ilosc_pobran" type="xsd:integer"/>
			<xsd:element name="srednia_cena">
				<xsd:complexType> 
					<xsd:simpleContent>
						<xsd:extension base="xsd:decimal">
							<xsd:attribute name="id" type="xsd:integer" /> 
							<xsd:attribute name="prod" type="xsd:string" default="yes"/> 
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="ogladalnosc" type="xsd:string" default="duÅ¼o"/>
			<xsd:element name="srednia_ocen" type="xsd:decimal"/>
			<xsd:element name="rok_produkcji" >
				<xsd:complexType> 
					<xsd:attribute name="nr" type="xsd:integer" /> 
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence> 
		<xsd:attribute name="type" type="xsd:string"/> 
		<xsd:attribute name="lang" type="attrValid"/> 
	</xsd:complexType> 

	<xsd:simpleType name="attrValid"> 
		<xsd:restriction base="xsd:string"> 
			<xsd:pattern value="[A-Z]{2}"/> 
		</xsd:restriction> 
	</xsd:simpleType> 

</xsd:schema>

=== pawel33317/XML-programy-kompilator-dtd-xml-schema-srcml/4 XSLT/zml4/zad3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><filmy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zad3.xsd">
	<film lang="EN" type="akcja">
		<tytul>Marsjanin</tytul>
		<ilosc_pobran>122</ilosc_pobran>
		<srednia_cena>18.52</srednia_cena>
		<ogladalnosc>36765</ogladalnosc>
		<srednia_ocen>7.6</srednia_ocen>
		<rok_produkcji nr="2015"/>
	</film>
	<film lang="EN" type="dramat">
		<tytul>Najdłuższa podróż</tytul>
		<ilosc_pobran>111</ilosc_pobran>
		<srednia_cena id="21">14.32</srednia_cena>
		<ogladalnosc>19923</ogladalnosc>
		<srednia_ocen>7.5</srednia_ocen>
		<rok_produkcji nr="2015"/>
	</film>
	<film lang="EN" type="komedia">
		<tytul>Praktykant</tytul>
		<ilosc_pobran>521</ilosc_pobran>
		<srednia_cena>17.44</srednia_cena>
		<ogladalnosc>23453</ogladalnosc>
		<srednia_ocen>7.5</srednia_ocen>
		<rok_produkcji nr="2015"/>
	</film> 
	<film lang="PL" type="dramat">
		<tytul>Układ zamknięty</tytul>
		<ilosc_pobran>28</ilosc_pobran>
		<srednia_cena id="21">14.33</srednia_cena>
		<ogladalnosc>17545</ogladalnosc>
		<srednia_ocen>7.4</srednia_ocen>
		<rok_produkcji nr="2013"/>
	</film>
<film lang="PL" type="horror"><tytul>Demonxx</tytul><ilosc_pobran>44</ilosc_pobran><srednia_cena>22.2</srednia_cena><ogladalnosc>23234</ogladalnosc><srednia_ocen>6.9</srednia_ocen><rok_produkcji nr="2016"/></film></filmy>
