=== pawel33317/XML-programy-kompilator-dtd-xml-schema-srcml/3 XMLSchema/zad3/zad3.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"> 
	<xsd:element name="filmy" type="typ_filmy"/> 
	<xsd:complexType name="typ_filmy"> 
		<xsd:sequence> 
			<xsd:element name="film" type="film_rozwiniecie" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence> 
		<xsd:attribute name="katalog" type="xsd:string" fixed="darmowe"/> 
	</xsd:complexType> 

	<xsd:element name="title" type="xsd:string"/> 
	<xsd:complexType name="film_rozwiniecie"> 
		<xsd:sequence> 
			<xsd:element ref="title" />
			<xsd:element name="ilosc" type="xsd:integer"/>
			<xsd:element name="srednia_cena">
				<xsd:complexType> 
					<xsd:simpleContent>
						<xsd:extension base="xsd:decimal">
							<xsd:attribute name="id" type="xsd:integer" /> 
							<xsd:attribute name="prod" type="xsd:string" default="yes"/> 
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="ogladalnosc" type="xsd:string" default="duÅ¼o"/>
			<xsd:element name="srednia_ocen" type="xsd:integer"/>
			<xsd:element name="najlepszy" >
				<xsd:complexType> 
					<xsd:attribute name="nr" type="xsd:integer" /> 
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="najgorszy" >
				<xsd:complexType> 
					<xsd:attribute name="nr" type="xsd:integer" /> 
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence> 
		<xsd:attribute name="type" type="xsd:string"/> 
		<xsd:attribute name="code" type="attrValid"/> 
	</xsd:complexType> 

	<xsd:simpleType name="attrValid"> 
		<xsd:restriction base="xsd:string"> 
			<xsd:pattern value="[a-z]{2}-\d{2}"/> 
		</xsd:restriction> 
	</xsd:simpleType> 

</xsd:schema>

=== pawel33317/XML-programy-kompilator-dtd-xml-schema-srcml/3 XMLSchema/zad3/zad3.xml
<?xml version="1.0" encoding="UTF-8"?>
<filmy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zad3.xsd">
	<film type="akcja" code="xc-22">
		<title>Akcja</title>
		<ilosc>423</ilosc>
		<srednia_cena id="21" prod="yes">15.33</srednia_cena>
		<ogladalnosc>duzy</ogladalnosc>
		<srednia_ocen>5</srednia_ocen>
		<najlepszy nr="23"/>
		<najgorszy nr="23"/>
	</film>
	<film type="melodramat" code="cs-22">
		<title>Melodramat</title>
		<ilosc>111</ilosc>
		<srednia_cena id="21">14.32</srednia_cena>
		<ogladalnosc>duzy</ogladalnosc>
		<srednia_ocen>1</srednia_ocen>
		<najlepszy nr="23"/>
		<najgorszy nr="23"/>
	</film>
	<film type="komedia">
		<title>Komedia</title>
		<ilosc>123</ilosc>
		<srednia_cena id="21">17.44</srednia_cena>
		<ogladalnosc>average</ogladalnosc>
		<srednia_ocen>5</srednia_ocen>
		<najlepszy nr="23"/>
		<najgorszy nr="23"/>
	</film> 
	<film type="dramat">
		<title>Dramat</title>
		<ilosc>411</ilosc>
		<srednia_cena id="21">16.13</srednia_cena>
		<ogladalnosc >small</ogladalnosc>
		<srednia_ocen>3</srednia_ocen>
		<najlepszy nr="23"/>
		<najgorszy nr="23"/>
	</film>
</filmy>
